import type { IntlText } from '../../core/entities/intl.js';

export const componentTexts = {
  pickDate: ['Date Picking', 'Выбор даты'],
  pickDatePeriod: ['Date Period Picking', 'Выбор диапазона дат'],
  decreaseValue: ['Decrease Value', 'Уменьшить значение'],
  increaseValue: ['Increase Value', 'Увеличить значение'],
  showWorldLocationsCount: [
    'Showing {shown} of {total} locations',
    '{shown, plural, one {Показана {shown} локация из {total}} few {Показаны {shown} локации из {total}} many {Показано {shown} локаций из {total}} other {Показано {shown} локаций из {total}}}',
  ],
  value: ['Value', 'Значение'],
  title: ['Title', 'Название'],
  editImage: ['Edit Image', 'Редактировать изображение'],
  exposure: ['Exposure ({value})', 'Экспозиция ({value})'],
  brightness: ['Brightness ({value})', 'Яркость ({value})'],
  contrast: ['Contrast ({value})', 'Контраст ({value})'],
  shadows: ['Shadows ({value})', 'Тёмные области ({value})'],
  highlights: ['Highlights ({value})', 'Светлые области ({value})'],
  saturation: ['Saturation ({value})', 'Насыщенность ({value})'],
  dark: ['Dark', 'Темно'],
  bright: ['Bright', 'Светло'],
  darker: ['Darker', 'Темнее'],
  brighter: ['Brighter', 'Светлее'],
  softer: ['Softer', 'Мягче'],
  stronger: ['Stronger', 'Сильнее'],
  blackAndWhite: ['B&W', 'Ч/Б'],
  vibrant: ['Vibrant', 'Насыщенно'],
  crop: ['Crop', 'Кадрирование'],
  zoom: ['Zoom (x{value})', 'Масштаб (x{value})'],
  compare: ['Compare', 'Сравнить'],
  change: ['Change', 'Изменить'],
  selectFile: ['Select File', 'Выбрать файл'],
  apply: ['Apply', 'Применить'],
  download: ['Download', 'Скачать'],
  reset: ['Reset', 'Сбросить'],
} satisfies Record<string, IntlText>;
