import type { IntlText } from '../../core/entities/intl.js';

export const editingTexts = {
  edit: ['Edit', 'Редактировать'],
  compileSelected: ['Compile Selected', 'Собрать подборку'],
  clearSelection: ['Clear Selection', 'Сбросить выделение'],
  mergeSelected: ['Merge Selected', 'Объединить выбранные'],
  createDraft: ['Create Draft', 'Создать черновик'],
  titleAndDescription: ['Title and Description', 'Название и описание на английском'],
  titleAndDescriptionRu: ['Title and Description in Russian', 'Название и описание'],
  share: ['Share', 'Поделиться'],
  submit: ['Submit', 'Отправить'],
  export: ['Export', 'Экспорт'],
  import: ['Import', 'Импорт'],
  localEdits: ['Edits', 'Правки'],
  localEditsHint: [
    'Make local edits, like creating drafts, then save them as a single patch. Share your patch to administrator or submit to repository when you are done.',
    'Внесите локальные правки, например создайте черновики, затем сохраните их как единый патч. Когда закончите, поделитесь патчем с администратором или отправьте его в репозиторий.',
  ],
  noEdits: ['No edits', 'Нет правок'],
  noEditsToCopy: ['No edits to copy.', 'Нет правок для копирования.'],
  noEditsToExport: ['No edits to export.', 'Нет правок для экспорта.'],
  noEditsToSave: ['No edits to save.', 'Нет правок для сохранения.'],
  noEditsToShare: ['No edits to share.', 'Нет правок, которыми можно поделиться.'],
  noEditsToSubmit: ['No edits to submit to repository.', 'Нет правок для отправки в репозиторий.'],
  noPatch: ['No patch', 'Нет патча'],
  savePatch: ['Save Patch', 'Сохранить патч'],
  savePatchTitle: ['Save Patch "{title}"', 'Сохранение патча "{title}"'],
  applyPatch: ['Apply Patch', 'Применить патч'],
  loadingPatch: ['Loading patch "{title}"', 'Загрузка патча "{title}"'],
  failedToLoadPatch: ['Failed to load patch "{title}": {error}', 'Не удалось загрузить патч "{title}": {error}'],
  applyingPatchTitle: ['Applying patch "{title}"', 'Применение патча "{title}"'],
  patchAlreadyLoaded: ['"{title}": Patch is already loaded.', '"{title}": Патч уже загружен.'],
  patchWrongOrExpired: ['"{name}": Patch is wrong or has expired.', '"{name}": Патч некорректен или устарел.'],
  exported: ['"{filename}": Patch exported', '"{filename}": Патч экспортирован'],
  importingFrom: ['Importing edits from "{filename}"', 'Импорт правок из "{filename}"'],
  exportingTo: ['Exporting edits to "{filename}"', 'Экспорт правок в "{filename}"'],
  mergeWithLocalEdits: [
    'Merge selected files with current local edits?',
    'Объединить выбранные файлы с текущими локальными правками?',
  ],
  saveLocalEdits: ['Save your local edits to patch?', 'Сохранить локальные правки в патч?'],
  clearLocalEdits: ['Clearing local edits', 'Очистка локальных правок'],
  resetLocalEditsAfterIssue: [
    'You were supposed to create a GitHub Issue containing your edits. Reset local edits?',
    'Предполагается, что вы создали GitHub Issue с вашими правками. Сбросить локальные правки?',
  ],
  edits: ['Edits', 'Правки'],
  editsWithCount: [
    '{count, plural, one {{count} edit} other {{count} edits}}',
    '{count, plural, one {{count} правка} few {{count} правки} other {{count} правок}}',
  ],
  copied: ['Edits copied to clipboard.', 'Правки скопированы в буфер обмена.'],
  shareLinkCopied: ['Share link copied to clipboard.', 'Ссылка скопирована в буфер обмена.'],
  githubIssueOpened: ['GitHub Issue creation page opened.', 'Страница создания GitHub Issue открыта.'],
  githubIssueUrlFailed: [
    'Failed to generate GitHub Issue creation url.',
    'Не удалось создать ссылку для GitHub Issue.',
  ],
  addOption: ['[Add]', '[Добавить]'],
  removeOption: ['[Remove]', '[Удалить]'],
  locationSelection: ['Location Picking', 'Выбор локации'],
  patchSelection: ['Patch Picking', 'Выбор патча'],
  authorSelection: ['Author Picking', 'Выбор автора'],
  locate: ['Locate', 'Указать локацию'],
  precise: ['Precise', 'Уточнить'],
  restore: ['Restore', 'Восстановить'],
  save: ['Save', 'Сохранить'],
  select: ['Select', 'Выделить'],
  unselect: ['Unselect', 'Снять выделение'],
  remove: ['Remove', 'Удалить'],
  creatingDraft: ['Creating Draft', 'Создание черновика'],
  postEditing: ['Post Editing', 'Редактирование поста'],
  locatingPost: ['Locating Post', 'Указание локации поста'],
  postPrecising: ['Post Precising', 'Уточнение поста'],
  resetLocalChanges: [
    'Are you sure you want to reset current local changes for this post?',
    'Сбросить текущие локальные правки для этого поста?',
  ],
  mergeSelectedConfirmation: [
    '{count, plural, one {Are you sure you want to merge {count} selected post?} other {Are you sure you want to merge {count} selected posts?}}',
    '{count, plural, one {Объединить {count} выбранный пост?} few {Объединить {count} выбранных поста?} many {Объединить {count} выбранных постов?} other {Объединить {count} выбранного поста?}}',
  ],
  editorsKey: ["Editor's key", 'Ключ редактора'],
  editorKeyHint: [
    'Used by editor to access full size drafts.',
    'Используется редактором для доступа к черновикам в полном размере.',
  ],
  validateEditorsKey: ['Validate', 'Проверить'],
  secretKeyCleared: ['Secret key cleared.', 'Секретный ключ очищен.'],
  secretKeySet: ['Secret key successfully tested and set.', 'Секретный ключ успешно проверен и сохранён.'],
  creatingRequest: ['Creating Request', 'Создание запроса'],
  insertLinks: ['Insert Links', 'Вставить ссылки'],
  mimeType: ['MIME Type', 'MIME-тип'],
  noChangesToSave: ['No changes to save.', 'Нет изменений для сохранения.'],
  noFilesSelectedForUpload: ['No files selected for upload', 'Не выбраны файлы для загрузки'],
  noLinksToInsert: ['No links to insert', 'Нет ссылок для вставки'],
  noResourceAccess: [
    "You have no access to this resource. Check out <setting>Editor's key setting</setting>.",
    'Нет доступа к этому ресурсу. Проверьте <setting>Ключ редактора</setting>.',
  ],
  pasteLinks: ['Paste Links', 'Вставить ссылки'],
  stopUploading: ['Stop Uploading', 'Остановить загрузку'],
  pending: ['Pending', 'Ожидает'],
  uploading: ['Uploading', 'Загружается'],
  size: ['Size', 'Размер'],
  uploaded: ['Uploaded', 'Загружено'],
  uploadError: ['Error', 'Ошибка'],
  expires: ['Expires', 'Будет удалено'],
  createEmail: ['Create email', 'Создать письмо'],
  createGithubIssue: ['Create GitHub Issue', 'Создать GitHub Issue'],
  talkToOrdinator: ['Talk to Ordinator', 'Поговорить с Ординатором'],
  selectFiles: ['Select Files', 'Выбрать файлы'],
  file: ['File', 'Файл'],
  status: ['Status', 'Статус'],
  processedFiles: ['Processed {processed} of {total} files', 'Обработано файлов: {processed} из {total}'],
  fileType: ['Type', 'Тип'],
  allowedFormats: ['Allowed Formats', 'Допустимые форматы'],
  shootingTips: ['Shooting Tips', 'Советы по съёмке'],
  strictRequirements: ['Strict Requirements', 'Строгие требования'],
  minimumRequirements: ['Minimum Requirements', 'Минимальные требования'],
  uploadFiles: ['Upload Files', 'Загрузить файлы'],
  patchTitle: ['Title', 'Название'],
  pickDate: ['Pick Date', 'Выбрать дату'],
  apply: ['Apply', 'Применить'],
  reset: ['Reset', 'Сбросить'],
} satisfies Record<string, IntlText>;
