import type { IntlText } from '../../core/entities/intl.js';

export const filteringTexts = {
  allPosts: ['All Posts', 'Все посты'],
  allOptions: ['All Options', 'Все фильтры'],
  anyLocation: ['Any', 'Любая'],
  anyPlacement: ['Any', 'Любое'],
  anyLocalEdits: ['Any', 'Любые'],
  customOptions: ['Custom Options ({count})', 'Свои фильтры ({count})'],
  inWork: ['In Work', 'В работе'],
  map: ['Map', 'Карта'],
  official: ['Official', 'Официальный'],
  orderBy: ['Order By', 'Сортировка по'],
  origin: ['Origin', 'Источник'],
  originals: ['Originals', 'Оригиналы'],
  preset: ['Preset', 'Пресет'],
  publishability: ['Publishability', 'Готовность'],
  ready: ['Ready', 'Готово'],
  recency: ['Recency', 'Свежесть'],
  reposts: ['Reposts', 'Повторы'],
  resetOptions: ['Reset Options', 'Сбросить фильтры'],
  requests: ['Requests', 'Запросы'],
  revisit: ['Revisit', 'Пересмотреть'],
  shortlist: ['Shortlist', 'Шорт-лист'],
  thirdParty: ['Third-Party', 'Сторонний'],
  editorsChoice: ["Editor's Choice", 'Выбор редактора'],
  edits: ['Edits', 'Правки'],
  unlocated: ['Unlocated', 'Без локации'],
  violations: ['Violations', 'Нарушения'],
  tags: ['Tags', 'Теги'],
  locations: ['Locations', 'Локации'],
  search: ['Search', 'Поиск'],
  searchingMembers: ['Searching Members', 'Поиск участников'],
  searchingPosts: ['Searching Posts', 'Поиск постов'],
  clear: ['Clear', 'Очистить'],
  collapse: ['Collapse', 'Свернуть'],
  expand: ['Expand', 'Развернуть'],
} satisfies Record<string, IntlText>;
