import type { IntlText } from '../../core/entities/intl.js';

export const highlightsTexts = {
  editorsChoicePost: ["Editor's Choice Post", 'Выбор редактора'],
  firstPost: ['First Post', 'Первый пост'],
  lastAchievement: ['Last Achievement', 'Последнее достижение'],
  lastClip: ['Last Clip', 'Последний клип'],
  lastCompilation: ['Last Compilation', 'Последняя подборка'],
  lastDraft: ['Last Draft', 'Последний черновик'],
  lastFulfilledRequest: ['Last Fulfilled Request', 'Последний выполненный запрос'],
  lastLocatedPost: ['Last Located Post', 'Последний пост с указанной локацией'],
  lastMention: ['Last Mention', 'Последнее упоминание'],
  lastMerch: ['Last Merch', 'Последний мерч'],
  lastNews: ['Last News', 'Последняя новость'],
  lastOriginalPost: ['Last Original Post', 'Последний оригинальный пост'],
  lastOuttakes: ['Last Outtakes', 'Последнее невошедшее'],
  lastPendingRequest: ['Last Pending Request', 'Последний ожидающий запрос'],
  lastPhotoshop: ['Last Photoshop', 'Последний фотомонтаж'],
  lastPost: ['Last Post', 'Последний пост'],
  lastRedrawing: ['Last Redrawing', 'Последняя перерисовка'],
  lastRejectedProposal: ['Last Rejected Proposal', 'Последнее отклонённое предложение'],
  lastRejectedRequest: ['Last Rejected Request', 'Последний отклонённый запрос'],
  lastShot: ['Last Shot', 'Последний кадр'],
  lastVideo: ['Last Video', 'Последнее видео'],
  lastWallpaper: ['Last Wallpaper', 'Последние обои'],
  lessLikedPost: ['Less Liked Post', 'Пост с минимумом лайков'],
  recentEditorsChoicePost: ["Recent Editor's Choice Post", 'Недавний выбор редактора'],
  recentEngagingPost: ['Recent Engaging Post', 'Недавний популярный пост'],
  topLikedPost: ['Top Liked Post', 'Пост с максимумом лайков'],
  topRatedPost: ['Top Rated Post', 'Пост с высшим рейтингом'],
} satisfies Record<string, IntlText>;
