import type { Field } from '../entities/field.js';
import type { IntlText } from '../entities/intl.js';

export const fieldTexts = {
  id: ['ID', 'ID'],
  title: ['Title', 'Заголовок на английском'],
  titleRu: ['Title in Russian', 'Заголовок'],
  description: ['Description', 'Описание на английском'],
  descriptionRu: ['Description in Russian', 'Описание'],
  name: ['Name', 'Имя на английском'],
  nameRu: ['Name in Russian', 'Имя'],
  nameRuFrom: ['Name in Russian in genitive', 'Имя в родительном падеже'],
  mark: ["Editor's Mark", 'Метка редактора'],
  aspect: ['Aspect Ratio', 'Формат'],
  type: ['Type', 'Тип'],
  author: ['Author', 'Автор'],
  location: ['Location', 'Локация'],
  placement: ['Placement', 'Расположение'],
  addon: ['Addon', 'Аддон'],
  violation: ['Violation', 'Нарушение'],
  locating: ['Locating', 'Указание локации'],
  request: ['Request', 'Запрос'],
  reject: ['Rejection', 'Отклонение'],
  announcement: ['Announcement', 'Анонс'],
  posts: ['Posts', 'Посты'],
  date: ['Date', 'Дата'],
  user: ['User', 'Пользователь'],
  text: ['Text', 'Текст'],
  service: ['Service', 'Сервис'],
  code: ['Code', 'Код'],
  mediaId: ['Media ID', 'Медиа ID'],
  created: ['Created', 'Создано'],
  published: ['Published', 'Опубликовано'],
  updated: ['Updated', 'Обновлено'],
  tags: ['Tags', 'Теги'],
  engine: ['Engine', 'Движок'],
  trash: ['Trash', 'Корзина'],
  content: ['Content', 'Контент'],
  snapshot: ['Snapshot', 'Снэпшот'],
  followers: ['Followers', 'Подписчики'],
  likes: ['Likes', 'Лайки'],
  views: ['Views', 'Просмотры'],
  reposts: ['Reposts', 'Репосты'],
  comments: ['Comments', 'Комментарии'],
  accessHash: ['Access Hash', 'Хеш доступа'],
  username: ['Username', 'Имя пользователя'],
  botChatId: ['Bot Chat ID', 'ID чата с ботом'],
  avatar: ['Avatar', 'Аватар'],
  admin: ['Administrator', 'Администратор'],
  profiles: ['Profiles', 'Профили'],
  deleted: ['Deleted', 'Удалено'],
  followed: ['Followed', 'Подписался'],
  unfollowed: ['Unfollowed', 'Отписался'],
  cell: ['Cell', 'Ячейка'],
} satisfies Record<Field, IntlText>;
