import type { IntlText } from '../entities/intl.js';

export const postFilterTexts = {
  original: [
    'original',
    '{count, plural, one {оригинальный} few {оригинальных} many {оригинальных} other {оригинального}}',
  ],
  reposted: ['reposted', '{count, plural, one {повторный} few {повторных} many {повторных} other {повторного}}'],
  publishable: [
    'publishable',
    '{count, plural, one {готовый к публикации} few {готовых к публикации} many {готовых к публикации} other {готового к публикации}}',
  ],
  notPublishable: [
    'not publishable',
    '{count, plural, one {не готовый к публикации} few {не готовых к публикации} many {не готовых к публикации} other {не готового к публикации}}',
  ],
  requested: [
    'requested',
    '{count, plural, one {запрошенный} few {запрошенных} many {запрошенных} other {запрошенного}}',
  ],
  unprompted: [
    'unprompted',
    '{count, plural, one {незапрошенный} few {незапрошенных} many {незапрошенных} other {незапрошенного}}',
  ],
  withAspect: ['with "{aspect}" aspect ratio', 'с форматом "{aspect}"'],
  withoutThirdPartyExpansions: ['without third-party expansions', 'без сторонних расширений'],
  withThirdPartyExpansions: ['with third-party expansions', 'со сторонними расширениями'],
  withAnyStatus: ['with any edits', 'с любыми правками'],
  withNoStatus: ['with no edits', 'без правок'],
  withStatus: ['with "{status}" edit', 'с правкой "{status}"'],
  withSearch: ['with "{search}" in title or description', 'с "{search}" в названии или описании'],
  withLocation: ['in "{location}"', 'в "{location}"'],
  withAnyLocation: ['in any location', 'в любой локации'],
  withUnknownLocation: ['in unknown location', 'в неизвестной локации'],
  withPlacement: ['placed {placement}', 'размещённых {placement}'],
  withAnyPlacement: ['with any placement', 'с любым расположением'],
  withUnknownPlacement: ['with unknown placement', 'с неизвестным расположением'],
  withMixedPlacement: ['with mixed placement', 'со смешанным расположением'],
  withAddon: ['with "{addon}" addon', 'с аддоном "{addon}"'],
  withAnyAddon: ['with any addon', 'с любым аддоном'],
  withNoAddon: ['with no addon', 'без аддона'],
  withTag: ['with "{tag}" tag', 'с тегом "{tag}"'],
  byUser: ['by "{user}"', 'от "{user}"'],
  locatedByUser: ['located by "{user}"', 'найденных пользователем "{user}"'],
  requestedByUser: ['requested by "{user}"', 'запрошенных пользователем "{user}"'],
  markedWith: ['marked with {mark}', 'с меткой {mark}'],
  withViolation: ['with "{violation}" violation', 'с нарушением "{violation}"'],
  withAnyViolation: ['with any violation', 'с любым нарушением'],
  withNoViolation: ['with no violations', 'без нарушений'],
  postedFromTo: ['from {from} to {to}', 'с {from} по {to}'],
  postedOn: ['on {date}', 'за {date}'],
  sortedBy: ['sorted by "{label}" {direction}', 'с сортировкой по полю "{label}" {direction}'],
  asc: ['ascending', 'по возрастанию'],
  desc: ['descending', 'по убыванию'],
} satisfies Record<string, IntlText>;
