import type { IntlText } from '../entities/intl.js';

export const postTexts = {
  post: ['Post', 'Пост'],
  posts: ['Posts', 'Посты'],
  tag: ['Tag', 'Тег'],
  located: ['Located', 'Найдено'],
  requested: ['Requested', 'Запрошено'],
  requestedBy: ['Requested By', 'Запросивший'],
  shot: ['Shot', 'Кадр'],
  shotUnit: [
    '{count, plural, one {shot} other {shots}}',
    '{count, plural, one {кадр} few {кадра} many {кадров} other {кадра}}',
  ],
  shots: ['Shots', 'Кадры'],
  compilation: ['Compilation', 'Подборка'],
  compilationUnit: [
    '{count, plural, one {compilation} other {compilations}}',
    '{count, plural, one {подборка} few {подборки} many {подборок} other {подборки}}',
  ],
  compilations: ['Compilations', 'Подборки'],
  clip: ['Clip', 'Клип'],
  clipUnit: [
    '{count, plural, one {clip} other {clips}}',
    '{count, plural, one {клип} few {клипа} many {клипов} other {клипа}}',
  ],
  clips: ['Clips', 'Клипы'],
  video: ['Video', 'Видео'],
  videoUnit: ['video', 'видео'],
  videos: ['Videos', 'Видео'],
  wallpaper: ['Wallpaper', 'Обои'],
  wallpaperUnit: ['wallpaper', 'обои'],
  wallpapers: ['Wallpapers', 'Обои'],
  verticalWallpaper: ['Vertical Wallpaper', 'Вертикальные обои'],
  redrawing: ['Redrawing', 'Перерисовка'],
  redrawingUnit: [
    '{count, plural, one {redrawing} other {redrawings}}',
    '{count, plural, one {перерисовка} few {перерисовки} many {перерисовок} other {перерисовки}}',
  ],
  redrawings: ['Redrawings', 'Перерисовки'],
  mention: ['Mention', 'Упоминание'],
  mentionUnit: [
    '{count, plural, one {mention} other {mentions}}',
    '{count, plural, one {упоминание} few {упоминания} many {упоминаний} other {упоминания}}',
  ],
  mentions: ['Mentions', 'Упоминания'],
  news: ['News', 'Новость'],
  newsUnit: [
    '{count, plural, one {news} other {news}}',
    '{count, plural, one {новость} few {новости} many {новостей} other {новости}}',
  ],
  newsPlural: ['News', 'Новости'],
  photoshop: ['Photoshop', 'Фотомонтаж'],
  photoshopUnit: [
    '{count, plural, one {photoshop} other {photoshops}}',
    '{count, plural, one {фотомонтаж} few {фотомонтажа} many {фотомонтажей} other {фотомонтажа}}',
  ],
  photoshops: ['Photoshops', 'Фотомонтажи'],
  outtakes: ['Outtakes', 'Невошедшее'],
  outtakesUnit: ['outtakes', 'невошедшее'],
  achievement: ['Achievement', 'Достижение'],
  achievementUnit: [
    '{count, plural, one {achievement} other {achievements}}',
    '{count, plural, one {достижение} few {достижения} many {достижений} other {достижения}}',
  ],
  achievements: ['Achievements', 'Достижения'],
  merch: ['Merch', 'Мерч'],
  merchUnit: ['merch', 'мерч'],
  indoors: ['Indoors', 'В помещении'],
  outdoors: ['Outdoors', 'На улице'],
  mixed: ['Mixed', 'Смешанное'],
} satisfies Record<string, IntlText>;
