export interface OrderingScenario {
  country: string;
  countryRu: string;
  services: string[];
}

export const orderingScenarios: OrderingScenario[] = [
  { country: 'Andorra', countryRu: 'Андорра', services: ['bt'] },
  { country: 'Armenia', countryRu: 'Армения', services: ['bt'] },
  { country: 'Australia', countryRu: 'Австралия', services: [] },
  { country: 'Austria', countryRu: 'Австрия', services: ['bt'] },
  { country: 'Azerbaijan', countryRu: 'Азербайджан', services: ['bt'] },
  { country: 'Belarus', countryRu: 'Беларусь', services: ['bt'] },
  { country: 'Belgium', countryRu: 'Бельгия', services: ['bt'] },
  { country: 'Bosnia and Herzegovina', countryRu: 'Босния и Герцеговина', services: ['bt'] },
  { country: 'Bulgaria', countryRu: 'Болгария', services: ['bt'] },
  { country: 'Canada', countryRu: 'Канада', services: ['bt'] },
  { country: 'China', countryRu: 'Китай', services: ['bt'] },
  { country: 'Croatia', countryRu: 'Хорватия', services: ['bt'] },
  { country: 'Czech Republic', countryRu: 'Чехия', services: ['bt'] },
  { country: 'Egypt', countryRu: 'Египет', services: ['bt'] },
  { country: 'Estonia', countryRu: 'Эстония', services: ['bt'] },
  { country: 'Finland', countryRu: 'Финляндия', services: [] },
  { country: 'France', countryRu: 'Франция', services: ['bt'] },
  { country: 'Georgia', countryRu: 'Грузия', services: ['bt'] },
  { country: 'Germany', countryRu: 'Германия', services: ['bt'] },
  { country: 'Greece', countryRu: 'Греция', services: ['bt'] },
  { country: 'Hungary', countryRu: 'Венгрия', services: ['bt'] },
  { country: 'India', countryRu: 'Индия', services: ['bt'] },
  { country: 'Indonesia', countryRu: 'Индонезия', services: ['bt'] },
  { country: 'Ireland', countryRu: 'Ирландия', services: ['bt'] },
  { country: 'Italy', countryRu: 'Италия', services: ['bt'] },
  { country: 'Japan', countryRu: 'Япония', services: ['bt'] },
  { country: 'Kazakhstan', countryRu: 'Казахстан', services: ['av'] },
  { country: 'Kosovo', countryRu: 'Косово', services: ['bt'] },
  { country: 'Kyrgyzstan', countryRu: 'Кыргызстан', services: ['bt'] },
  { country: 'Latvia', countryRu: 'Латвия', services: ['bt'] },
  { country: 'Lithuania', countryRu: 'Литва', services: ['bt'] },
  { country: 'Luxembourg', countryRu: 'Люксембург', services: ['bt'] },
  { country: 'Moldova', countryRu: 'Молдова', services: ['bt'] },
  { country: 'Montenegro', countryRu: 'Черногория', services: ['bt'] },
  { country: 'Morocco', countryRu: 'Марокко', services: ['bt'] },
  { country: 'Netherlands', countryRu: 'Нидерланды', services: ['bt'] },
  { country: 'North Macedonia', countryRu: 'Северная Македония', services: ['bt'] },
  { country: 'Norway', countryRu: 'Норвегия', services: ['bt'] },
  { country: 'Poland', countryRu: 'Польша', services: [] },
  { country: 'Portugal', countryRu: 'Португалия', services: ['bt'] },
  { country: 'Romania', countryRu: 'Румыния', services: ['bt'] },
  { country: 'Russia', countryRu: 'Россия', services: ['av'] },
  { country: 'Serbia', countryRu: 'Сербия', services: ['bt'] },
  { country: 'Slovakia', countryRu: 'Словакия', services: ['bt'] },
  { country: 'Slovenia', countryRu: 'Словения', services: ['bt'] },
  { country: 'South Korea', countryRu: 'Южная Корея', services: ['bt'] },
  { country: 'Spain', countryRu: 'Испания', services: ['bt'] },
  { country: 'Sweden', countryRu: 'Швеция', services: ['bt'] },
  { country: 'Switzerland', countryRu: 'Швейцария', services: ['bt'] },
  { country: 'Tajikistan', countryRu: 'Таджикистан', services: ['bt'] },
  { country: 'Thailand', countryRu: 'Таиланд', services: ['bt'] },
  { country: 'Turkey', countryRu: 'Турция', services: ['bt'] },
  { country: 'Ukraine', countryRu: 'Украина', services: [] },
  { country: 'United Arab Emirates', countryRu: 'Объединённые Арабские Эмираты', services: ['bt'] },
  { country: 'United Kingdom', countryRu: 'Великобритания', services: ['bt'] },
  { country: 'United States of America', countryRu: 'Соединённые Штаты Америки', services: ['bt'] },
  { country: 'Uzbekistan', countryRu: 'Узбекистан', services: ['bt'] },
];
