export interface OrderingScenario {
  country: string;
  services: string[];
}

export const orderingScenarios: OrderingScenario[] = [
  { country: 'Andorra', services: ['bt'] },
  { country: 'Armenia', services: ['bt'] },
  { country: 'Australia', services: [] },
  { country: 'Austria', services: ['bt'] },
  { country: 'Azerbaijan', services: ['bt'] },
  { country: 'Belarus', services: ['bt'] },
  { country: 'Belgium', services: ['bt'] },
  { country: 'Bosnia and Herzegovina', services: ['bt'] },
  { country: 'Bulgaria', services: ['bt'] },
  { country: 'Canada', services: ['bt'] },
  { country: 'China', services: ['bt'] },
  { country: 'Croatia', services: ['bt'] },
  { country: 'Czech Republic', services: ['bt'] },
  { country: 'Egypt', services: ['bt'] },
  { country: 'Estonia', services: ['bt'] },
  { country: 'Finland', services: [] },
  { country: 'France', services: ['bt'] },
  { country: 'Georgia', services: ['bt'] },
  { country: 'Germany', services: ['bt'] },
  { country: 'Greece', services: ['bt'] },
  { country: 'Hungary', services: ['bt'] },
  { country: 'India', services: ['bt'] },
  { country: 'Indonesia', services: ['bt'] },
  { country: 'Ireland', services: ['bt'] },
  { country: 'Italy', services: ['bt'] },
  { country: 'Japan', services: ['bt'] },
  { country: 'Kazakhstan', services: ['av'] },
  { country: 'Kosovo', services: ['bt'] },
  { country: 'Kyrgyzstan', services: ['bt'] },
  { country: 'Latvia', services: ['bt'] },
  { country: 'Lithuania', services: ['bt'] },
  { country: 'Luxembourg', services: ['bt'] },
  { country: 'Moldova', services: ['bt'] },
  { country: 'Montenegro', services: ['bt'] },
  { country: 'Morocco', services: ['bt'] },
  { country: 'Netherlands', services: ['bt'] },
  { country: 'North Macedonia', services: ['bt'] },
  { country: 'Norway', services: ['bt'] },
  { country: 'Poland', services: [] },
  { country: 'Portugal', services: ['bt'] },
  { country: 'Romania', services: ['bt'] },
  { country: 'Russia', services: ['av'] },
  { country: 'Serbia', services: ['bt'] },
  { country: 'Slovakia', services: ['bt'] },
  { country: 'Slovenia', services: ['bt'] },
  { country: 'South Korea', services: ['bt'] },
  { country: 'Spain', services: ['bt'] },
  { country: 'Sweden', services: ['bt'] },
  { country: 'Switzerland', services: ['bt'] },
  { country: 'Tajikistan', services: ['bt'] },
  { country: 'Thailand', services: ['bt'] },
  { country: 'Turkey', services: ['bt'] },
  { country: 'Ukraine', services: [] },
  { country: 'United Arab Emirates', services: ['bt'] },
  { country: 'United Kingdom', services: ['bt'] },
  { country: 'United States of America', services: ['bt'] },
  { country: 'Uzbekistan', services: ['bt'] },
];
