name: Patch Data
description: Apply JSON patch to project's data.
title: data-patch
labels:
  - data-patch
body:
  - type: input
    id: name
    attributes:
      label: Data Patch URL or Name
      description: Write down saved data patch sharing URL or name.
      placeholder: mwscr-patch-cc6fe487.json
  - type: textarea
    id: text
    attributes:
      label: Data Patch Text
      description: Write down data patch (JSON).
      render: json
