name: Locate Post
description: Select where the shot was done.
title: POST_ID
labels:
  - post-location
body:
  - type: textarea
    id: postLocation
    attributes:
      label: Location
      description: List of game locations
      render: txt
