name: Propose Post
description: Write post or post group title, which you would like to propose.
labels:
  - post-proposal
body:
  - type: textarea
    id: text
    attributes:
      label: Images
      description: What images would you like to propose?
      placeholder: >-
        Paste public links or attach images or ZIP archives with images. Only
        .png and .zip files are allowed.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Author'
  - type: input
    id: userName
    attributes:
      label: Name
      description: >-
        Write down your preferred user name. Leave blank if you have contributed
        with issues earlier.
      placeholder: Jiub the Saint
  - type: input
    id: userProfileIg
    attributes:
      label: Instagram Profile
      description: >-
        Write down your Instagram profile name. Leave blank if you have
        contributed with issues earlier.
      placeholder: jiub
  - type: input
    id: userProfileTg
    attributes:
      label: Telegram Profile
      description: >-
        Write down your Telegram profile name. Leave blank if you have
        contributed with issues earlier.
      placeholder: saint_jiub
  - type: input
    id: userProfileVk
    attributes:
      label: VK Profile
      description: >-
        Write down your VK profile name. Leave blank if you have contributed
        with issues earlier.
      placeholder: cliffracer_destroyer
