name: Request Post
description: Describe in the title, which post you would like to request.
title: Cool to see, how cliffracer dies!
labels:
  - post-request
body:
  - type: dropdown
    id: postType
    attributes:
      label: Post Type
      options:
        - shot
        - shot-set
        - redrawing
        - video
        - clip
        - wallpaper
        - wallpaper-v
        - news
        - mention
        - photoshop
        - outtakes
        - achievement
      default: 0
    validations:
      required: true
  - type: input
    id: userName
    attributes:
      label: Name
      description: >-
        Write down your preferred user name. Leave blank if you have contributed
        with issues earlier.
      placeholder: Jiub the Saint
  - type: input
    id: userProfileIg
    attributes:
      label: Instagram Profile
      description: >-
        Write down your Instagram profile name. Leave blank if you have
        contributed with issues earlier.
      placeholder: jiub
  - type: input
    id: userProfileTg
    attributes:
      label: Telegram Profile
      description: >-
        Write down your Telegram profile name. Leave blank if you have
        contributed with issues earlier.
      placeholder: saint_jiub
  - type: input
    id: userProfileVk
    attributes:
      label: VK Profile
      description: >-
        Write down your VK profile name. Leave blank if you have contributed
        with issues earlier.
      placeholder: cliffracer_destroyer
