name: Review Post
description: Paste in the title the ID of post.
title: POST_ID
labels:
  - post-review
body:
  - type: input
    id: postMark
    attributes:
      label: Editor's Mark
      placeholder: A1 A2 B1 B2 C D E F
  - type: input
    id: postViolation
    attributes:
      label: Violation
      placeholder: >-
        Inappropriate content JPEG artifacts Graphic issues No anti-aliasing
        Non-vanilla look Uses or requires mods UI is visible Unclear request
        Unreachable resource Unsupported resource
