name: resolve-issue

concurrency:
  group: maintain

on:
  issues:
    types: [edited, reopened, labeled]

jobs:
  resolve-issue:
    if:
      contains(github.event.issue.labels.*.name, 'data-patch') || contains(github.event.issue.labels.*.name,
      'post-proposal') || contains(github.event.issue.labels.*.name, 'post-request') ||
      contains(github.event.issue.labels.*.name, 'post-editing') || contains(github.event.issue.labels.*.name,
      'post-location') || contains(github.event.issue.labels.*.name, 'post-merging')
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION_CONTEXT: ${{ toJson(github) }}
      GITHUB_BOT_EMAIL: '${{ secrets.BOT_EMAIL }}'
      GITHUB_BOT_NAME: '${{ secrets.BOT_NAME }}'
      SITE_FTP_HOST: '${{ secrets.SITE_FTP_HOST }}'
      SITE_FTP_USER: '${{ secrets.SITE_FTP_USER }}'
      SITE_FTP_PASSWORD: '${{ secrets.SITE_FTP_PASSWORD }}'
      SITE_FTP_PATH: '${{ secrets.SITE_FTP_PATH }}'
      SITE_FTP_STORE_PATH: '${{ secrets.SITE_FTP_STORE_PATH }}'
      YANDEX_DISK_STORE_PATH: '${{ secrets.YANDEX_DISK_STORE_PATH }}'
      YANDEX_DISK_ACCESS_TOKEN: '${{ secrets.YANDEX_DISK_ACCESS_TOKEN }}'
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Resolve issue and commit changes
        # To use BOT user name and email
        # git config user.email ${{ env.GITHUB_BOT_EMAIL }}
        # git config user.name ${{ env.GITHUB_BOT_NAME }}
        run: |
          npm run resolve-github-issue
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore(resolve-issue): resolve #${{ github.event.issue.number }}"
          git pull --rebase -X ours
          git push

      - name: Build site
        run: npm run build

      - name: Deploy site
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SITE_SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'dist/client/'
          REMOTE_HOST: ${{ secrets.SITE_SSH_HOST }}
          REMOTE_USER: ${{ secrets.SITE_SSH_USER }}
          TARGET: ${{ secrets.SITE_SSH_PATH }}
          EXCLUDE: '/store/'
          SCRIPT_BEFORE: 'ls>/dev/null'
